# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'
name: xacte-local

services:
  # # Reverse proxy
  # nginx-reverseproxy:
  #   container_name: xacte-reverseproxy
  #   image: par.petal.local/xacte/server/reverseproxy:latest
  #   build:
  #     context: .
  #     dockerfile: Tools/nginx/Dockerfile
  #   ports:
  #     - 81:80
  #   depends_on:
  #     - local-xacte.api.patient
  #   restart: always

  #################
  # Web application
  local-xacte.web.wasm:
    container_name: xacte-web
    image: par.petal.local/xacte/web/wasm:latest
    # build:
    #   context: .
    #   dockerfile: Web/src/Xacte.Web/Server/Dockerfile
    depends_on:
      - local-xacte.api.gateway
    ports:
      - 8000:8000
      - 9000:9000
    expose:
      - 5100
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://*:9000;http://*:8000;http://*:5100
      - ASPNETCORE_HTTPS_PORT=9000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=xacte4ever
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  #########
  # Gateway
  local-xacte.api.gateway:
    container_name: xacte-gateway
    image: par.petal.local/xacte/api/gateway:latest
    # build:
    #   context: .
    #   dockerfile: ApiGateway/src/Xacte.ApiGateway/Dockerfile
    depends_on:
      - local-xacte.api.patient
    ports:
      - 8001:8001
      - 9001:9001
    expose:
      - 5101
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://*:9001;http://*:8001;http://*:5101
      - ASPNETCORE_HTTPS_PORT=9001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=xacte4ever
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  #####
  # Api
  local-xacte.api.patient:
    container_name: xacte-patient
    image: par.petal.local/xacte/api/patient:latest
    # build:
    #   context: .
    #   dockerfile: Patient/src/Xacte.Patient.Api/Dockerfile
    ports:
      - 8100:8100
      - 9100:9100
    expose:
      - 5102
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=https://*:9100;http://*:8100;http://*:5102
      - ASPNETCORE_HTTPS_PORT=9100
      - ASPNETCORE_Kestrel__Certificates__Default__Password=xacte4ever
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro