FROM nginx:alpine

COPY Tools/nginx/nginx.conf /etc/nginx/nginx.conf
# COPY Tools/nginx/aspnetapp.crt /etc/ssl/certs/aspnetapp.crt
# COPY Tools/nginx/aspnetapp.key /etc/ssl/private/aspnetapp.key
# COPY Tools/nginx/global.pass /etc/keys/global.pass